- name: create cert and config directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: true
  with_items:
    - "/var/opt/magma/certs"

- name: copy keys to certificate directory
  copy:
    src: "/etc/ssl/certs/cacert"
    dest: "/var/opt/magma/certs/rootCA.pem"
  become: true