- name: allocate key
  ec2_key:
    name: "{{ key_name }}"
  register: key_val
  tags: [never, keyCreate]

- name: find keyBoot id
  command: aws ec2 describe-key-pairs --key-names "{{ key_name }}" --query 'KeyPairs[0].KeyPairId' --output text
  register: key_id
  tags: [never, keyCreate]

- name: Tag keyBoot
  ec2_tag:
    resource: "{{ key_id.stdout }}"
    tags:
      agw: "docker"
  tags: [never, keyCreate]

- name: copy .pem file
  copy:
    content: "{{ key_val.key.private_key }}"
    dest: "{{ dirLocalInventory }}/{{ key_name }}.pem"
    mode: 0600
  when: key_val.changed
  tags: [never, keyCreate]